Add CDE docs
AdobeDocs/commerce-services pull request #101
Opened 2024-05-01 22:01 UTC by le0n4ik

## Purpose of this pull request

This pull request (PR) ...

## Affected pages

- ...

## Links to Magento Open Source code

- ...

2024-05-07 18:45 UTC, mslabko requested changes

2024-05-07 18:45 UTC, mslabko commented on src/pages/catalog-data-export/multi-thread.md
> +Multithreading is supported for all 3 ways (see details) to sync data to SaaS:
Let's add cross link to data synchinization page (workflow)

2024-05-07 18:45 UTC, mslabko commented on src/pages/catalog-data-export/troubleshooting-and-logging.md
> +Out-of-the-box extension provides the following operations you can see in logs file:
```suggestion
Explanation of different operation types:
```

2024-05-07 18:45 UTC, mslabko commented on src/pages/catalog-data-export/troubleshooting-and-logging.md
> +### TBD: Add NewRelic info
Let's add details:

```
If you store Adobe Commerce logs in New Relic, it may be beneficial to add parsing rules to improve readability and query experience 

- login to New Relice
- Go to `Logs => Parsing`
- Click `Create parsing rule`


**Filter logs based on NRQL**
`filePath LIKE '%commerce-data-export%.log'`

**Parsing rule**
`\[%{DATA:timestamp}\] report.%{DATA:logLevel} %{GREEDYDATA:feed:json}`

After adding this rule you will be able to query by specific feed type, operation, etc
For example:
`feed.feed:"products" and feed.status:"Complete"`

```

2024-05-07 18:45 UTC, mslabko commented on src/pages/catalog-data-export/troubleshooting-and-logging.md
> +If you see that some entities are not sent to SaaS or data exporter entities have any code different from _success_ (200) in the status field of the data exporter table. It makes sense to turn in ext
@le0n4ik , we can copy what we have in https://experienceleague.adobe.com/en/docs/commerce-merchant-services/user-guides/data-services/catalog-sync#troubleshooting to this page

2024-05-07 18:45 UTC, mslabko commented on src/pages/catalog-data-export/pricing-index.md
> +TBD
@meker12 probably we need to incorporate https://experienceleague.adobe.com/en/docs/commerce-merchant-services/price-indexer/price-indexing to new structure, however, this is not directly related to data exporter. Any suggestions?

2024-05-08 17:32 UTC, merged

2024-05-08 18:35 UTC, le0n4ik commented on src/pages/catalog-data-export/commerce-data-export-overview.md
> +The Commerce Data Export extension is a tool designed to facilitate the synchronization of data between Adobe Commerce and SaaS Commerce Service. It collects and exports various types of data, referr
Done

2024-05-08 18:55 UTC, le0n4ik commented on src/pages/catalog-data-export/commerce-data-export-overview.md
> +- The extension provides two interfaces for data synchronization: a [UI-based interface](https://experienceleague.adobe.com/en/docs/commerce-admin/systems/data-transfer/data-dashboard) and a CLI-inte
@mslabko It's mentioned and separated in the workflow.md (https://github.com/AdobeDocs/commerce-services/pull/101/files#diff-e4103969b2b69c09892e1bce34d0f95b396714d7558b3c2b2c14c1ac0ea96cecR14)
Here - is just a basic overview. I can put a note, that full resync is for initial sync only.

2024-05-08 19:22 UTC, le0n4ik commented on src/pages/catalog-data-export/workflow.md
> +    - "indexer_reindex_all_invalid" job
Done

2024-05-08 19:23 UTC, le0n4ik commented on src/pages/catalog-data-export/workflow.md
> +# Workflow
Done

2024-05-08 19:24 UTC, le0n4ik commented on src/pages/catalog-data-export/commands-and-options.md
> +### Entity feeds sync modes
Done

2024-05-08 19:28 UTC, le0n4ik commented on src/pages/catalog-data-export/multi-thread.md
> +Multithreading is supported for all 3 ways (see details) to sync data to SaaS:
done

2024-05-08 19:30 UTC, le0n4ik commented on src/pages/catalog-data-export/troubleshooting-and-logging.md
> +### TBD: Add NewRelic info
Done

2024-05-08 19:38 UTC, le0n4ik commented on src/pages/catalog-data-export/troubleshooting-and-logging.md
> +If you see that some entities are not sent to SaaS or data exporter entities have any code different from _success_ (200) in the status field of the data exporter table. It makes sense to turn in ext
Done

2024-05-09 14:24 UTC, meker12 commented on src/pages/catalog-data-export/pricing-index.md
> +TBD
As discussed with Alex, I think the Price Index and Catalog Adapter documentation should be surfaced on the Commerce Services landing page. Right now the only entry points to that documentation are links from existing topics.  So there's no way to find the documentation.  

Is the Pricing Index service on the same level as Catalog Service.  

Question -- Can you use the data export extension independently like you can the Catalog Service and Pricing  Service?  -- so there's the Feed Ingestion API -- is that equivalent to the Commerce Service data export service?