Adding beta content for new search filters
AdobeDocs/commerce-services pull request #140
Opened 2024-09-09 15:56 UTC by erikmarr

## Purpose of this pull request

This pull request (PR) documents new filtering capability within the `productSearch` query.

## Affected pages

- https://developer.adobe.com/commerce/services/graphql/live-search/product-search/#filtering

2024-09-10 12:58 UTC, sgonzalezmangana approved these changes

2024-09-10 13:43 UTC, erikmarr commented on src/pages/_images/srch-in-srch.png
Thanks for the review @sgonzalezmangana! It is a Radwell screenshot. Do we have an example of this search within a search in Luma?

2024-09-10 22:02 UTC, jhadobe requested changes

2024-09-10 22:28 UTC, keharper commented
The installation and setup instructions belong in other topics. 

You need to add the new fields to the SearchClauseInput section.

2024-09-11 21:27 UTC, erikmarr commented
@keharper great point. I've created a companion PR here for the installation information: https://git.corp.adobe.com/AdobeDocs/commerce-merchant-services.en/pull/628

2024-09-16 17:01 UTC, alexj74 commented on src/pages/graphql/live-search/product-search.md
> +
@erikmarr I would phrase line times 169 - 173 slightly differently (explaining this new capability is tricky for sure 🙃 )

> This beta adds two new conditions to the filtering section of the `productSearch` query. These new conditions let you filter product attributes using contains and startsWith

Possible update to the above:
> This beta supports two new capabilities:
>* **Layered search:** Ability to search within another search context. With this capability you can undertake up to two layers of search for your search queries. 
Example: Layer 1 search: ‘motor’ on ‘product attribute 1’. Layer 2 search: ‘part number 123’ on ‘product attribute 2’. Here you are searching for all the products for the search query - 'part number 123' on ‘product attribute 2’ on a list of products which is already filtered based on the search query ‘motor’ on ‘product attribute 1’.
>* **StartsWith search indexation**:  This new technical capability of implementing a StartsWith indexation unlocks two functional capabilities:
    (1) starts with search: Ability to let shoppers search for products where the attribute value starts with a particular string
    (2) ends with search: Ability to let shoppers search for products where the attribute value ends with a particular string. For this, the product attribute needs to be ingested in reverse and the API call should also be a reversed string. 
Detailed examples for both are provided in the sections below

2024-09-16 21:44 UTC, erikmarr commented on src/pages/graphql/live-search/product-search.md
> +##### endsWith filter example
I agree. I'm waiting to get access to a build. I plan to publish this as is then provide full query responses for GA.

2024-09-19 00:56 UTC, alexj74 commented on src/pages/graphql/live-search/product-search.md
> +  - Merchants to configure an ends with search so shoppers can search for products where the attribute value ends with a particular string. To enable an ends with search, the product attribute needs
Minor: can you add quotes for `ends with`->`'ends with'`
It helps with the readability of the sentence

2024-09-19 00:57 UTC, alexj74 commented on src/pages/graphql/live-search/product-search.md
> +This beta supports two new capabilities:
`This beta supports two new capabilities:` -> `This beta supports three new capabilities:`

2024-09-19 01:19 UTC, alexj74 commented on src/pages/graphql/live-search/product-search.md
> +
Content for the **third** capability:

> **contains search indexation** - Ability to search an attribute using contains indexation. This new capability allows:
>- Shoppers to search for a query within a larger string. Example: Search for product number 'PE-123' in the string `HAPE-123`

2024-09-19 01:20 UTC, alexj74 commented on src/pages/graphql/live-search/product-search.md
> +- **startsWith search indexation** - Ability to search using `startsWith` indexation. This new capability allows:
```suggestion
- **startsWith search indexation** - Ability to search using `startsWith` indexation. To enable this for a product attribute, check the 'Starts with' checkbox in Admin UI. This new capability allows:
```

2024-09-19 01:28 UTC, alexj74 commented on src/pages/graphql/live-search/product-search.md
> +
Could you add a line which says:

> Layered search is available for both **startsWith search indexation**  and **contains search indexation** which are described below.

2024-09-19 01:52 UTC, alexj74 commented on src/pages/graphql/live-search/product-search.md
> +- Each aggregation returns a maximum of 1000 facets.
- `startsWith` and `contains` both require a minimum of 2 characters in the search.
- `startsWith` will allow a maximum of 10 characters for search.
- `contains` will allow a maximum of 10 characters for search. If more than 10 characters are passed in, the search results will be returned for an autocomplete search result and not a true `contains` search.

2024-09-19 02:17 UTC, alexj74 commented on src/pages/graphql/live-search/product-search.md
> +For installation information, see the [Live Search guide](https://experienceleague.adobe.com/en/docs/commerce-merchant-services/live-search/install#install-the-live-search-beta) in the merchant docum
Below line 183 I would add:
- `Autocomplete` search is enabled by default and cannot be modified. With this you can use `contains` in the [search filter](https://developer.adobe.com/commerce/services/graphql/live-search/product-search/#filtering). Here the search query in the contains will return an autocomplete type search response. We recommend the use of this type of search for description type fields which have a long text (>50 characters).
- `Contains` search when enabled will allow a true 'phrase contained in a string' search. With this you can use `contains` in the [search filter](https://developer.adobe.com/commerce/services/graphql/live-search/product-search/#filtering) and it will allow a true  'phrase contained in a string' search instead of an autocomplete search.
- `Starts with` search when enabled will allow you to query strings which start with a particular value. With this you can use `startsWith` in the [search filter](https://developer.adobe.com/commerce/services/graphql/live-search/product-search/#filtering).

2024-09-19 03:27 UTC, alexj74 commented on src/pages/graphql/live-search/product-search.md
> +This beta supports two new capabilities:
```suggestion
This beta supports three new capabilities:
```

2024-09-19 18:25 UTC, erikmarr commented on src/pages/graphql/live-search/product-search.md
> +For installation information, see the [Live Search guide](https://experienceleague.adobe.com/en/docs/commerce-merchant-services/live-search/install#install-the-live-search-beta) in the merchant docum
This seems out of place here. I think this would be best when we talk about the checkboxes in the Admin.

2024-09-19 19:29 UTC, jhadobe approved these changes

2024-09-19 19:43 UTC, merged