DCAT-2088: Add instructions for generating API references
AdobeDocs/commerce-services pull request #167
Opened 2024-11-25 21:38 UTC by meker12

## Purpose of this pull request

- Add instructions for building the auto-generated GraphQL API references for the CCDM APIs
- Change default layout of Data Ingestion API Reference to stacked to reduce page width and minimize need for horizontal scrolling after selecting an API reference link.

## Affected pages

- [Data ingestion API Reference](https://developer-stage.adobe.com/commerce/services/composable-catalog/data-ingestion/api-reference/)

2024-11-25 22:28 UTC, dshevtsov requested changes

2024-11-25 22:28 UTC, dshevtsov commented on README.md
> +- `adobe-theme`: [custom theme](https://github.com/anvilco/spectaql/blob/main/examples/themes/README.md).
We haven't been using a custom theme in this project yet.

2024-11-25 22:28 UTC, dshevtsov commented on README.md
> +- `schema.json`: the GraphQL schema extracted from the Adobe Commerce (B2B) instance.
We use a URL to the resources that return schemas instead of storing a schema file in this project.

2024-11-25 22:28 UTC, dshevtsov commented on README.md
> +The resulting GraphQL API reference lives in the `static/graphql-api/` directory.
This project contains two references.

2024-11-25 22:28 UTC, dshevtsov commented on README.md
> +It is embedded into the `/graphql/reference` page using the `frameSrc` feature on the DevSite.
Wrong path to the page. There are two pages with references.

2024-11-25 22:28 UTC, dshevtsov commented on README.md
> +To rebuild the GraphQL API references after any updates, use yarn to run the following build scripts as needed:
```suggestion
To rebuild the GraphQL API references after any updates, use yarn locally to run the following build scripts as needed:
```

2024-11-25 22:28 UTC, dshevtsov commented on README.md
> +```shell
Add text descriptions for each yarn script name instead of the actual script code.
Example: 
- `build:admin-api` - build the Admin API reference.

2024-11-25 22:28 UTC, dshevtsov commented on README.md
> +If either of these endpoints change, be sure to update the Spectaql config file and rebuild the API reference guides.
It's not clear why you should update the config file.

2024-11-25 22:28 UTC, dshevtsov commented on README.md
> +After the PR is merged, someone from the documentation team will publish the changes to the documentation server.
```suggestion
After the PR is merged, the documentation team will publish the changes to the documentation website.
```

2024-11-25 22:28 UTC, dshevtsov commented on README.md
> +### Resources
Duplication of the Resources clause.

2024-11-25 22:28 UTC, dshevtsov commented on src/openapi/README.md
> +The Data Ingestion API auto-generated API Reference is embedded into the Composable Catalog Data Model documentation using the RedoclyAPIBlock
```suggestion
The Data Ingestion API auto-generated API Reference is embedded into the Composable Catalog Data Model documentation using the [RedoclyAPIBlock](https://github.com/adobe/aio-theme?tab=readme-ov-file#redoclyapiblock)
```

2024-11-25 22:28 UTC, dshevtsov commented on src/openapi/README.md
> +DevSite feature.
```suggestion
feature.
```
DevSite seems to be our internal term AFAIK.

2024-11-25 22:28 UTC, dshevtsov commented on src/openapi/README.md
> +The OpenAPI schema source file (`data-ingestion-schema-v1.yaml`) is maintained by development and currently resides in developer documentation source repository
```suggestion
The OpenAPI schema source file (`data-ingestion-schema-v1.yaml`) is maintained by engineering and currently resides in developer documentation source repository
```

2024-11-25 22:28 UTC, dshevtsov commented on src/openapi/README.md
> +1. Create anbranch from the `ccdm-early-access` branch.
```suggestion
1. Create a branch from the `ccdm-early-access` branch.
```

2024-11-25 22:28 UTC, dshevtsov commented on src/openapi/README.md
> +1. Regenerate API reference locally and test changes:
```suggestion
1. To regenerate API reference locally and test changes you can use the following command:
```

2024-11-25 22:28 UTC, dshevtsov commented on src/openapi/README.md
> +
Note, the `@redocly/cli` has limited functionality comparing to the toolkit integrated in the website's infrastructure via RedoclyAPIBlock .

2024-11-25 22:28 UTC, dshevtsov commented on src/openapi/README.md
> +7. Request devdocs review.
```suggestion
7. Request review from the Commerce Documentation team.
```

2024-11-25 22:28 UTC, dshevtsov commented on src/openapi/README.md
> +   [developer-stage site](https://developer-stage.adobe.com/commerce/services/composable-catalog/) for Early Access customers.
I'd expect here a link to the generated REST API reference.

2024-11-26 18:07 UTC, dshevtsov requested changes

2024-11-26 18:07 UTC, dshevtsov commented on src/openapi/README.md
> +   npx @redocly/cli build-docs src/openapi/data-ingestion-schema-v1.yaml --config src/openapi/.redocly.yaml
That's where you need the `.redocly.yaml`. But it must be consistent with the configuration attributes provided in the RedoclyAPIBlock.

2024-11-26 18:59 UTC, meker12 commented on README.md
> +**Tip:** When you encounter unexpected failures or delays, try to clean up the gatsby and yarn caches with the command: `yarn clean && yarn cache clean` for troubleshooting.
```suggestion
**Tip:** If you encounter unexpected failures or delays, try to clean up the gatsby and yarn caches with the command: `yarn clean && yarn cache clean` for troubleshooting.
```

2024-11-26 19:01 UTC, meker12 commented on src/openapi/README.md
> +   npx @redocly/cli build-docs src/openapi/data-ingestion-schema-v1.yaml --config src/openapi/.redocly.yaml
I'll add the .redocly.yaml back.  For now, I'll just add the settings we have in the RedoclyAPIBlock settings. Maybe some of those settings should be included in the RedoclyAPIBlock.

2024-11-26 19:20 UTC, dshevtsov reviewed
It would be beneficial to also add the prerequisites.

1. Node.js of version set in [.nvmrc](/.nvmrc).
1. yarn

2024-11-26 19:31 UTC, meker12 commented on src/openapi/README.md
> +   **NOTE:** The @redocly/cli tool has limited functionality comparing to the toolkit integrated in the website's infrastructure via RedoclyAPIBlock.
```suggestion
   **NOTE:** The @redocly/cli tool has limited functionality compared to the toolkit integrated in the website's infrastructure via RedoclyAPIBlock.
```

2024-11-26 20:33 UTC, dshevtsov requested changes

2024-11-26 20:33 UTC, dshevtsov commented on README.md
>  `
```suggestion

```

2024-11-26 20:33 UTC, dshevtsov commented on README.md
> +- [Storefront API reference](https://github.com/AdobeDocs/commerce-services/edit/ccdm-early-access/src/pages/composable-catalog/storefront-services/api-reference.md) `frameSrc: /graphql-api/storefron
```suggestion
```
Duplication

2024-11-26 20:33 UTC, dshevtsov commented on README.md
>  `
Redundant symbol

2024-11-26 20:33 UTC, dshevtsov commented on src/openapi/.redocly.yaml
> +    disableSidebar: true
```suggestion
    disableSidebar: true

```
EOF

2024-11-26 20:33 UTC, dshevtsov commented on src/openapi/.redocly.yaml
Here is the configuration options available for the redoc CLI: https://github.com/Redocly/redoc/blob/main/docs/config.md

2024-11-26 21:33 UTC, meker12 commented on README.md
> +`
```suggestion
```

2024-11-26 23:01 UTC, dshevtsov requested changes
Suggested some changes.
Also, reminding about the prerequisites I mentioned before. They can significantly improve first time experience by avoiding unexpected failures since the project uses an outdated Node.js version.

2024-11-27 15:24 UTC, dshevtsov requested changes

2024-11-27 15:24 UTC, dshevtsov commented on README.md
> +- Node.js that matches the version set in the [.nvmrc](https://github.com/AdobeDocs/commerce-services/blob/main/.nvmrc) npm configuration file.
```suggestion
- Node.js that matches the version set in the [.nvmrc](https://github.com/AdobeDocs/commerce-services/blob/main/.nvmrc) ([nvm](https://github.com/nvm-sh/nvm) configuration file).
```

2024-11-27 15:24 UTC, dshevtsov commented on src/openapi/README.md
> +For local builds, ensure that your environment has the following installed:
This is not necessary for npx commands because it does not use either Yarn or dependencies from package.json.

2024-11-27 22:43 UTC, merged