First round of updates
AdobeDocs/commerce-services pull request #2
Opened 2022-05-10 15:54 UTC by keharper

## Description

This PR deletes unnecessary files that are part of the default template.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-05-10 20:03 UTC, jeff-matthews requested changes

2022-05-10 20:03 UTC, jeff-matthews commented on gatsby-config.js
> +  pathPrefix: process.env.PATH_PREFIX || '/commerce/contributor/'
```suggestion
  pathPrefix: process.env.PATH_PREFIX || '/commerce/services/'
```

2022-05-10 20:03 UTC, jeff-matthews commented on gatsby-config.js
> +const { versions, pages, subPages } = require("./src/data/navigation");
You actually created the navigation directory inside `src/pages/guides/data/` instead of `src/data`, which is causing the build to fail. Please move it so it's consistent with other projects.

2022-05-11 22:01 UTC, jeff-matthews requested changes

2022-05-11 22:01 UTC, jeff-matthews commented on src/data/navigation/sections/index.js
> +const guides = require("./guides");
You haven't created this file either, so local builds are failing.

2022-05-11 22:03 UTC, jeff-matthews commented
@dshevtsov, this is a good example of why we need to prioritize finishing the PR validation GitHub Actions workflow for the template repo.

The workflow I've implemented in the commerce-marketplace and commerce-contributor repos would've caught the navigation errors here.

2022-05-12 18:28 UTC, jeff-matthews commented
@jeff-matthews, since I started working in the new commerce-php repo, I decided to attempt to add additional validation for link checking and compilation/build. I don't expect this to be the final version, but it'll give you an idea about what I want to see in the validation for all of our repos.

https://github.com/AdobeDocs/commerce-php/pull/3/files#diff-1e798a1ad0dd7f41499fa143183c20c65d5ef93c148c8f99ad2c21fdd8b965fa

2022-05-13 20:52 UTC, keharper commented
Closing this PR. Creating the wrong directory structure had made it too difficult for me to get it right.

2022-05-13 20:52 UTC, closed without merging