Add customizable options to Catalog Service schema
AdobeDocs/commerce-services pull request #97
Opened 2024-04-19 13:15 UTC by meker12

## Purpose of this pull request

Added customizable options field descriptions to product and refine product queries, and added the inputOptions data to the query and response output. 

## Affected pages

- [products query](https://developer.adobe.com/commerce/services/graphql/catalog-service/products/)
-[refineProducts query](https://developer.adobe.com/commerce/services/graphql/catalog-service/products/)

## Links to Magento Open Source code

https://git.corp.adobe.com/magento-datalake/catalog-storefront-api-service/pull/152

2024-04-19 21:14 UTC, meker12 commented on src/_includes/graphql/catalog-service/product-view.md
> +Product input options provide a way for shoppers to customize a a product before adding it to a cart. They are based on a variation of a single SKU. For example, the shopper can provide a custom imag
```suggestion
Product input options provide a way for shoppers to customize a a product before adding it to a cart. They are based on a variation of a single SKU. For example, the shopper can provide a custom image or text to personalize a product. These input options can be associated with a price increase or decrease if a markdown amount is specified.
```

2024-04-19 21:21 UTC, meker12 commented on src/_includes/graphql/catalog-service/product-view.md
> +`values` | [ProductViewOptionValue Interface] | List of available option values.
```suggestion
`values` | [`[ProductViewOptionValue!]`](#productviewoptionvalue-Interface)] | List of available option values.
```

2024-04-24 08:00 UTC, consra commented on src/_includes/graphql/catalog-service/product-view.md
> +Product input options provide a way for shoppers to customize a product before adding it to a cart. When specified, the options create a variant of a single SKU. For example, the shopper can provide
A suggestion: "A customization option" -> "A customizable option"

2024-04-24 08:25 UTC, consra commented on src/pages/graphql/catalog-service/products.md
> +                    }
Fix Indentation

2024-04-24 08:25 UTC, consra commented on src/pages/graphql/catalog-service/products.md
> +            inputOptions {
Fix Indentation

2024-04-24 08:26 UTC, consra commented on src/pages/graphql/catalog-service/products.md
> +                    "inputOptions": [
Fix indention

2024-04-24 08:27 UTC, consra commented on src/pages/graphql/catalog-service/products.md
> +                    "inputOptions": [
"inputOptions" should have the same indentation as "attributes"

2024-04-24 08:28 UTC, consra commented on src/pages/graphql/catalog-service/products.md
> +                fileExtensions
Here is something bad. Maybe you are missing a "}"

2024-04-24 08:38 UTC, consra requested changes
Changes requested

2024-04-24 08:40 UTC, consra commented
"Technical review -- Check the updated query and response changes for customization options and provide updates if necessary. Would it be better to add a new query specifically for the customization options use case?"

Check the inline commets. We can leave it as it is.

2024-04-24 11:26 UTC, asilaghi approved these changes
+1

2024-04-24 11:26 UTC, asilaghi commented on src/_includes/graphql/catalog-service/product-view.md
> +`images(roles: [String])` | [`ProductViewImage`](#productviewimage-type) | A list of images defined for the product.
not sure why you removed [ ], the datatype is an array of 'ProductViewImage'

2024-04-24 13:41 UTC, meker12 commented on src/_includes/graphql/catalog-service/product-view.md
> +Product input options provide a way for shoppers to customize a product before adding it to a cart. When specified, the options create a variant of a single SKU. For example, the shopper can provide
```suggestion
Product input options provide a way for shoppers to customize a product before adding it to a cart. When specified, the options create a variant of a single SKU. For example, the shopper can provide a custom image or text to personalize a product. A customizable option can include an associated markdown amount that is applied to increase or decrease the product price.
```

2024-04-24 13:45 UTC, meker12 commented on src/_includes/graphql/catalog-service/product-view.md
> +`quantity` | []`SimpleProductView`](#simpleproductview-type) | Default quantity of an option value.
```suggestion
`quantity` | [`SimpleProductView`](#simpleproductview-type) | Default quantity of an option value.
```

2024-04-24 15:06 UTC, meker12 commented on src/_includes/graphql/catalog-service/product-view.md
> +`images(roles: [String])` | [`ProductViewImage`](#productviewimage-type) | A list of images defined for the product.
Mistake when I added the links. I'll go and fix other occurrences also.

2024-04-24 17:40 UTC, keharper commented on src/_includes/graphql/catalog-service/product-view.md
> +`inputOptions` | [`ProductViewInputOption`](#productviewinputoption-type)
Alphabetize

2024-04-24 17:40 UTC, keharper commented on src/_includes/graphql/catalog-service/product-view.md
> +`inputOptions` | [`ProductViewInputOption`](#productviewinputoption-type) | A list of input options the shopper can supply to customize a product.
Alphabetize

2024-04-24 17:40 UTC, keharper commented on src/_includes/graphql/catalog-service/product-view.md
> +`width` |  Int | Width of image provided for an input option
Alphabetize

2024-04-24 17:40 UTC, keharper commented on src/_includes/graphql/catalog-service/product-view.md
> +`inputOptions
this is an incomplete line, and also out of alphabetical order

2024-04-25 15:24 UTC, meker12 commented on src/_includes/graphql/catalog-service/product-view.md
> +Product input options provide a way for shoppers to customize a product before adding it to a cart. When specified, the options create a variant of a single SKU. For example, the shopper can provide
```suggestion
Product input options provide a way for shoppers to customize a product before adding it to a cart. When specified, the options create a variant of a single SKU. For example, the shopper can provide a custom image or text to personalize a product. A customizable option can include an associated markdown amount that is applied to the product price.
```

2024-04-25 18:28 UTC, keharper approved these changes

2024-04-25 18:28 UTC, keharper commented on src/_includes/graphql/catalog-service/product-view.md
> +Product input options provide a way for shoppers to customize a product before adding it to a cart. When specified, the options create a variant of a single SKU. For example, the shopper can provide
The paragraph says markdown, but the field is `markupAmount`.

When a product is designated as being customizable, the admin defines whether the customized product has a separate SKU. 

Maybe replace the 2nd sentence with

A product definition can contain details about the how the shopper enters customization details.

2024-04-25 21:28 UTC, merged

2024-04-26 11:07 UTC, consra commented on src/pages/graphql/catalog-service/products.md
> +            }
The indentation for this part is pretty bad. 
It should look this way
`... on ComplexProductView {
        inputOptions {
            id
            title
            required
            type
            markupAmount
            suffix
            sortOrder
            range {
                from
                to
            }
            imageSize {
                width
                height
            }
            fileExtensions
       }`

2024-04-26 15:24 UTC, meker12 commented on src/pages/graphql/catalog-service/products.md
> +            }
I'll fix this -- I thought I had actually.